apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-war-main
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: resources
    repoURL: http://github.com/jfdenise/my-war
    targetRevision: main_deployment
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
